name: Farm
main: me.oddlyoko.farm.Farm
version: 0.1
author: 0ddlyoko
api-version: 1.13
commands:
  farm:
    description: Help Farm
permissions:
  farm.create:
    default: op
    description: Create a new farm
  farm.remove:
    default: op
    description: Remove an existing farm
  farm.tree:
    default: op
    description: Add / Remove a tree from the list
  farm.reload:
    default: op
    description: Reload all farms